library(ncdf)
library(raster)
#
source("./config_list_filter11.r")
source("./freqhist_function.R")
#..............................................................................
fh<-create.hist.freq(date.begin=date.b.string,
                     date.end=date.e.string,
                     input.path=ob.input.path,
                     input.filename=ob.input.filename,
                     input.filetype=2,
                     hist.file=ob.output.histtmp,
                     hist.breaks=precipitation.breaks,
                     lower.bound=precipitation.dailydef,
                     filter.scale=11)
#..............................................................................
quit(status=0)
